### ISSUE TITLE
build failure.

### ISSUE THREAD

**Issue by stephensong** [wincentbalin/compile-static-audiowaveform#2]
I keep getting the following error on Step 91/228:

    configure: error: in `/tmp/compile/fontconfig-2.12.6':
    configure: error: The pkg-config script could not be found or is too old.  Make sure it
    is in your PATH or set the PKG_CONFIG environment variable to the full 
    path to pkg-config.

If I look further up the log, I also see:

    checking pkg-config is at least version 0.9.0... ./configure: /tmp/compile/bin/i686-w64- 
   mingw32-pkg-config: /bin/sh^M: bad interpreter: No such file or directory
    no

I did some googling, and came to the view that it was a problem with line-endings (cr-lf vs lf) in the file "pkg-config".  Alas, I tried changing the line-endings (both ways), and when that didn't fix it, I erased all the docker images and started from scratch.  Alas, still no cigar. 

Any ideas / suggestions would be most welcome!

thanks.

**Comment by wincentbalin** [comment]
Hello Stephen, it seems that the recent changes fix your problem. Could you please verify it?

**Comment by FrankDupree** [comment]
Hi, i seem to be having errors building the application. i suspect its the same error. cant seem to find a way to read the error as the console window closes immediately. Tried copying the output to a file, still no cigar :(..Is there way i can get the error so i can paste here, also it would be nice if you could just attach the compiled binaries and dll's. I'd like to use the dll's in a c# application. any pointers? thanks for the good Job!

**Comment by FrankDupree** [comment]
Finally got the error to show!
```
[91mconfigure: error: in `/tmp/compile/fontconfig-2.12.6':
[0m[91mconfigure: error: The pkg-config script could not be found or is too old.  Make sure it
is in your PATH or set the PKG_CONFIG environment variable to the full
path to pkg-config.

Alternatively, you may set the environment variables FREETYPE_CFLAGS
and FREETYPE_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

To get pkg-config, see <http://pkg-config.freedesktop.org/>.
See `config.log' for more details
[0m
```

**Comment by wincentbalin** [comment]
Hello Frank, what is your compilation environment?

And thank you for the compliments!

**Comment by FrankDupree** [comment]
I'm using docker for windows (Linux containers). don't know if this helps.
![Capture](https://user-images.githubusercontent.com/8538930/71075423-4ed1e680-2184-11ea-8e7d-1da33463cb92.PNG)

**Comment by wincentbalin** [comment]
I should also point out that this setup compiles static binaries, without any DLLs.

**Comment by FrankDupree** [comment]
my application is going to run on a linux server eventually, for the sake of development that's done on a windows machine, any idea how i can wrap this into lets say an api call? have it run in docker, i don't know, anything!..can you enhance this repository to include DLLs?

**Comment by wincentbalin** [comment]
Try to convert line endings of pkg-config script to UNIX.

**Comment by wincentbalin** [comment]
@FrankDupree You should raise the issue of compilation as shared library in the main repository, as this repository only gives you a setup for compilation of static executables.

**Comment by FrankDupree** [comment]
Done: seems to be building now.
```
ex pkg-config <<EOF
:set fileformat=unix
:wq
EOF
```
https://stackoverflow.com/questions/17579553/windows-command-to-convert-unix-line-endings

**Comment by FrankDupree** [comment]
> @FrankDupree You should raise the issue of compilation as shared library in the main repository, as this repository only gives you a setup for compilation of static executables.

Okay will do this.

**Comment by FrankDupree** [comment]
@wincentbalin Thank you! successfully compiled!
Will figure out a way to call the application via c# then port once its deployed to a linux environment.
