### ISSUE TITLE
failed to prepare y060sby1okziprdyhgbqrsd35: max depth exceeded

### ISSUE THREAD

**Issue by CamiloMolinaGomez** [wincentbalin/compile-static-audiowaveform#5]
Hey folks, when compiling the app I receive the following error:

![image](https://user-images.githubusercontent.com/34034887/152834383-d7fad04d-e197-4588-887c-1007e56a2eaf.png)

any idea to resolve that?

**Comment by chrisn** [comment]
My fork has a fix for this issue: https://github.com/chrisn/compile-static-audiowaveform. If you can, though, I'd recommend using the pre-built Windows binaries at https://github.com/bbc/audiowaveform/releases.

**Comment by CamiloMolinaGomez** [comment]
Thankyou @chrisn, it works for me :)
